# Numpy - Library to handle arrays.
- statically typed (element types can't be mixed or altered)
- non resizeable (can't append or remove elements)
- much faster than python's dynamically typed lists 
- support use of vector operations.

In [1]:
import numpy as np

my_array = np.array([5, 2, 6, 8])
my_array.dtype


array([5, 2, 6, 8])

In [3]:
a2 = np.random.random(20)
a3 = np.random.randint(10, 20, 10)
a3

array([14, 18, 13, 15, 14, 16, 13, 12, 12, 13])

In [ ]:
a4 = np.zeroes(10)
a5 = np.ones(10)
a5

In [ ]:
a6 = np.linspace(0, 10, 100)
a7 = np.arange(0, 10, 0.2)


## Vectorized operations

In [4]:
x = [2, 4, 7, 1, 7, 3, 2, 5, 2]
x * 2

[2, 4, 7, 1, 7, 3, 2, 5, 2, 2, 4, 7, 1, 7, 3, 2, 5, 2]

In [ ]:
y = [value * 2 for value in x]
y

In [ ]:
x = np.array([2, 4, 7, 1, 7, 3, 2, 5, 2])
x

In [ ]:
import matplotlib.pyplot as plt

x = np.linspace(-10, 10, 1000)

plt.plot(x, x**2)
plt.grid(True)

## Array indexing and slicing 
- Indexing and slciing works just as we are used to from python lists.
- However, we can also use a list of indexes when indexing a numpy array.
- Boolean mask / boolean indexing can be used to filter through data in arrays.

In [11]:
x = np.array([2, 4, 7, 1, 7, 3, 2, 5, 2])
x

array([2, 4, 7, 1, 7, 3, 2, 5, 2])

In [ ]:
# Filtering using a list of indexes:
x[[0, 2, 0, -1, 1]]

In [ ]:
# Boolean indexing:
x[[False, False,  True, False,  True, False, False,  True, False]]

In [ ]:
# Boolean mask can be created when using comparison operators on numpy arrays
x >= 5

In [ ]:
# Boolean mask can be created when using comparison operators on numpy arrays
x >= 5

## Aggregation methods
An aggregation method is a method that takes a list/array of values and by doing some calculation, returning a single value.

In [ ]:
x = np.array([2, 4, 7, 1, 7, 3, 2, 5, 2])
x

In [ ]:
print(f"{x.sum() = }")
print(f"{x.min() = }")
print(f"{x.max() = }")
print(f"{x.mean() = }")

## Multidimensional arrays

In [16]:
array_1d = np.array([2, 4, 7, 1, 7, 3, 2, 5, 2])
array_1d

array([1, 7, 3, 2])

In [ ]:
array_2d = np.array([[2, 4, 7, 1, 7], [3, 2, 5, 2, 6]])
array_2d

In [ ]:
random_2d = np.random.randint(0, 10, [5, 4])
random_2d

In [1]:
random_2d = np.random.randint(0, 10, [5, 4])
random_2d

NameError: name 'np' is not defined

## Slicing of 2d-array

In [ ]:
random_2d

In [ ]:
# Indexing in a 2d-array
random_2d[-1, 1]

In [ ]:
# Slicing in a 2d array
random_2d[:3, 1:] = 0

In [ ]:
random_2d